// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Errors that can happen while performing card abilities
 */
export type AssetAbilityError = { "AlreadyConfirmedAssetIndex": number };

/**
 * Representation of an asset card. Each asset has a gold and a silver value, as well as an
 * associated color. Some cards alse have an [`AssetPowerup`].
 */
export type AssetCard = { 
/**
 * Title of the asset card.
 */
title: string, 
/**
 * The gold value of the asset.
 */
gold_value: number, 
/**
 * The silver value of the asset.
 */
silver_value: number, 
/**
 * The color of the asset.
 */
color: Color, 
/**
 * Whether or not this asset has an [`AssetPowerup`].
 */
ability: AssetPowerup | null, 
/**
 * Url containing the relative location of the card in the assets folder
 */
image_front_url: string, 
/**
 * Url containing the relative location of the back of the card in the assets folder
 */
image_back_url: string, };

/**
 * A certain powerup some assets have. These specify special actions this asset allows a player to
 * take at the end of the game.
 */
export type AssetPowerup = "At the end of the game, for one color, turn - into 0 or 0 into +" | "At the end of the game, turn silver into gold on one asset card" | "At the end of the game, count one of your assets as any color";

/**
 * A card type used in relation to actions taken with player's hands. Can either be `Asset` or
 * `Liability`.
 */
export type CardType = "Asset" | "Liability";

/**
 * A type that represents the changes made with the [`ChangeAssetColor`] asset ability. It contains
 * the index of the asset that was changed, as well as its original color.
 */
export type ChangeAssetColorData = { 
/**
 * The index of the asset in question.
 */
asset_idx: number, 
/**
 * The color of the asset in question.
 */
color: Color, };

/**
 * An enum containing all characters currently in the game in the order in which they are called.
 */
export type CharacterType = "Shareholder" | "Banker" | "Regulator" | "CEO" | "CFO" | "CSO" | "HeadRnD" | "Stakeholder";

/**
 * Represtation of the colors associated with all assets as well as some selectable characters.
 */
export type Color = "Red" | "Green" | "Purple" | "Yellow" | "Blue";

/**
 * The connect response. The very first thing a client should send is this request.
 */
export type Connect = { "action": "Connect", "data": { 
/**
 * The username of the player who wants to connect.
 */
username: string, 
/**
 * The channel code of the player who wants to connect.
 */
channel: string, } };

/**
 * A response type that a player receives after performing an action. Can either be an error or
 * a confirmation that the action was succesful, including the data needed to update the UI
 * accordingly.
 */
export type DirectResponse = { "action": "Error", "data": ResponseError } | { "action": "YouStartedGame" } | { "action": "YouSelectedCharacter", "data": { 
/**
 * The character this player selected.
 */
character: CharacterType, } } | { "action": "YouFiredCharacter", "data": { 
/**
 * The character that was fired.
 */
character: CharacterType, } } | { "action": "YouRegulatorOptions", "data": { 
/**
 * The options this player has to swap with other players.
 */
options: Array<RegulatorSwapPlayer>, 
/**
 * Always [`Character::Regulator`]
 */
character: CharacterType, 
/**
 * A string containing information about what this character is allowed to do.
 */
perk: string, } } | { "action": "YouSwapDeck", "data": { 
/**
 * The amount of cards this player may draw from the deck.
 */
cards_to_draw: number, } } | { "action": "YouSwapPlayer", "data": { 
/**
 * The new hand of the player.
 */
new_cards: Array<EitherAssetLiability>, } } | { "action": "YouAreDivesting", "data": { 
/**
 * A list of cards for each player, which can either be or not be divested.
 */
options: Array<DivestPlayer>, 
/**
 * Always [`Character::Stakeholder`]
 */
character: CharacterType, 
/**
 * A string containing information about what this character is allowed to do.
 */
perk: string, } } | { "action": "YouDrewCard", "data": { 
/**
 * The card that was drawn
 */
card: EitherAssetLiability, 
/**
 * Whether this player can draw another card.
 */
can_draw_cards: boolean, 
/**
 * Whether this player should still give back any cards.
 */
can_give_back_cards: boolean, } } | { "action": "YouPutBackCard", "data": { 
/**
 * The index of the card this player put back.
 */
card_idx: number, 
/**
 * Whether this player can draw another card.
 */
can_draw_cards: boolean, 
/**
 * Whether this player should still give back any cards.
 */
can_give_back_cards: boolean, } } | { "action": "YouCharacterAbility", "data": { 
/**
 * The character of the player.
 */
character: CharacterType, 
/**
 * A string containing information about what this player is allowed to do.
 */
perk: string, } } | { "action": "YouBoughtAsset", "data": { 
/**
 * The asset this player bought.
 */
asset: AssetCard, 
/**
 * If the market changed, a list of events and a new market is returned.
 */
market_change: MarketChange | null, } } | { "action": "YouIssuedLiability", "data": { 
/**
 * The liability the player issued.
 */
liability: LiabilityCard, } } | { "action": "YouAreFiringSomeone", "data": { 
/**
 * The list of available characters to fire.
 */
characters: Array<CharacterType>, 
/**
 * Always [`Character::Shareholder`]
 */
character: CharacterType, 
/**
 * A string containing information on what this character is allowed to do.
 */
perk: string, } } | { "action": "YouDivestedAnAsset", "data": { 
/**
 * The amount of gold it cost to divest this asset.
 */
gold_cost: number, } } | { "action": "YouAreTerminatingSomeone", "data": { 
/**
 * A list of characters whose credit can be terminated.
 */
characters: Array<CharacterType>, 
/**
 * Always [`Character::Banker`]
 */
character: CharacterType, 
/**
 * A string containing information on what this character is allowed to do.
 */
perk: string, } } | { "action": "YouRedeemedLiability", "data": { 
/**
 * The index of the liability that was redeemed.
 */
liability_idx: number, } } | { "action": "YouEndedTurn" } | { "action": "YouMinusedIntoPlus", "data": { 
/**
 * The market color that was changed,
 */
color: Color, 
/**
 * The new market for this player.
 */
new_market: MarketCard, 
/**
 * The updated player score.
 */
new_score: number, } } | { "action": "YouSilveredIntoGold", "data": { 
/**
 * The data of the old asset that should be updated. When no card was selected before this
 * action, this value will be `None`.
 */
old_asset_data: SilverIntoGoldData | null, 
/**
 * The data of the new asset that should be updated. When a card was deselected, this value
 * will be `None`.
 */
new_asset_data: SilverIntoGoldData | null, 
/**
 * The updated player score.
 */
new_score: number, } } | { "action": "YouChangedAssetColor", "data": { 
/**
 * The data of the old asset that should be updated. When no card was selected before this
 * action, this value will be `None`.
 */
old_asset_data: ChangeAssetColorData | null, 
/**
 * The data of the new asset that should be updated. When a card was deselected, this value
 * will be `None`.
 */
new_asset_data: ChangeAssetColorData | null, 
/**
 * The updated player score.
 */
new_score: number, } } | { "action": "YouConfirmedAssetAbility", "data": { 
/**
 * The asset the player confirmed their choice for.
 */
asset_idx: number, } };

/**
 * Represents an asset that can be divested from a certain player including the cost of doing so.
 */
export type DivestAsset = { 
/**
 * The asset in question.
 */
asset: AssetCard, 
/**
 * The cost of divisting this asset based.
 */
divest_cost: number, 
/**
 * Whether or not this asset is divestable.
 */
is_divestable: boolean, };

/**
 * Errors related to divesting assets.
 */
export type DivestAssetError = "InvalidCharacter" | "InvalidPlayerCharacter" | "AlreadyDivestedThisTurn" | "CantDivestAssetType" | "NotEnoughCash" | "InvalidCardIdx";

/**
 * Utility struct used to represent each asset that can be divested from a player including the
 * cost of doing so.
 */
export type DivestPlayer = { 
/**
 * The id of the particular player.
 */
player_id: PlayerId, 
/**
 * The list of [`DivestAsset`]s for this player, which are all assets that can be divested
 * from this player including the cost of doing so.
 */
assets: Array<DivestAsset>, };

/**
 * Errors related to drawing cards.
 */
export type DrawCardError = { "MaximumCardsDrawn": number };

/**
 * A nicer tagged representation of `Either<Asset, Liability>` which looks much better when
 * serialized.
 */
export type EitherAssetLiability = { "card_type": "asset" } & AssetCard | { "card_type": "liability" } & LiabilityCard;

/**
 * The event card type
 */
export type EventCard = { 
/**
 * The title of the event
 */
title: string, 
/**
 * A narration of the event which describes what happens
 */
description: string, 
/**
 * A set of colors that gain gold because of this event
 */
plus_gold: Array<Color>, 
/**
 * A set of colors that lose gold because of this event
 */
minus_gold: Array<Color>, 
/**
 * A character that skips their turn because of this event
 */
skip_turn: CharacterType | null, };

/**
 * Errors related to firing a character.
 */
export type FireCharacterError = "InvalidCharacter" | "InvalidPlayerCharacter" | "AlreadyFiredThisTurn";

/**
 * Requests that are sent from the frontend, to be handled by the backend.
 */
export type FrontendRequest = { "action": "StartGame" } | { "action": "SelectCharacter", "data": { 
/**
 * The character the player wants to select.
 */
character: CharacterType, } } | { "action": "DrawCard", "data": { 
/**
 * The [`CardType`] the player wants to draw.
 */
card_type: CardType, } } | { "action": "PutBackCard", "data": { 
/**
 * The index of the card this player is trying to put back.
 */
card_idx: number, } } | { "action": "BuyAsset", "data": { 
/**
 * The index of the card the player wants to buy.
 */
card_idx: number, } } | { "action": "IssueLiability", "data": { 
/**
 * The index of the card the player wants to issue.
 */
card_idx: number, } } | { "action": "RedeemLiability", "data": { 
/**
 * The index of the issued liability the player wanst to redeem.
 */
liability_idx: number, } } | { "action": "UseAbility" } | { "action": "FireCharacter", "data": { 
/**
 * The character that is to be fired.
 */
character: CharacterType, } } | { "action": "SwapWithDeck", "data": { 
/**
 * The list of card indices to be swapped with the deck.
 */
card_idxs: Array<number>, } } | { "action": "SwapWithPlayer", "data": { 
/**
 * The id of the player which is to be swapped with.
 */
target_player_id: PlayerId, } } | { "action": "DivestAsset", "data": { 
/**
 * The id of the player which would be forced to divest their asset.
 */
target_player_id: PlayerId, 
/**
 * The index of the asset that is to be divested.
 */
card_idx: number, } } | { "action": "EndTurn" } | { "action": "MinusIntoPlus", "data": { 
/**
 * The color to change the minus from.
 */
color: Color, } } | { "action": "SilverIntoGold", "data": { 
/**
 * The index of the asset to change silver into gold from.
 */
asset_idx: number, } } | { "action": "ChangeAssetColor", "data": { 
/**
 * The index of the asset to change color from.
 */
asset_idx: number, 
/**
 * The new color of the asset.
 */
color: Color, } } | { "action": "ConfirmAssetAbility", "data": { 
/**
 * The index of the asset which ability was used.
 */
asset_idx: number, } };

/**
 * The main error enum used by the game logic.
 */
export type GameError = { "Lobby": LobbyError } | { "SelectingCharacters": SelectingCharactersError } | { "PlayCard": PlayCardError } | { "RedeemLiability": RedeemLiabilityError } | { "GiveBackCard": GiveBackCardError } | { "DrawCard": DrawCardError } | { "FireCharacter": FireCharacterError } | { "Swap": SwapError } | { "DivestAsset": DivestAssetError } | { "CardAbility": AssetAbilityError } | { "InvalidAssetIndex": number } | { "InvalidPlayerCount": number } | { "InvalidPlayerIndex": number } | { "InvalidPlayerName": string } | "PlayerMissingCharacter" | "NotPlayersTurn" | "PlayerShouldGiveBackCard" | "NotLobbyState" | "NotSelectingCharactersState" | "NotRoundState" | "NotResultsState" | "NotAvailableInLobbyState" | "NotAvailableInResultsState";

/**
 * Errors that can happen when a player must give back a card.
 */
export type GiveBackCardError = { "InvalidCardIndex": number } | "Unnecessary";

/**
 * Representation of a liability card. Each liability has an associated gold value as well as a
 * [`LiabilityType`], which determines how expensive it is to issue this liability.
 */
export type LiabilityCard = { 
/**
 * Gold value of this liability
 */
value: number, 
/**
 * The card's [`LiabilityType`], which determines how expensive it is to issue this liability.
 */
rfr_type: LiabilityType, 
/**
 * Url containing the relative location of the card in the assets folder.
 */
image_front_url: string, 
/**
 * Url containing the relative location of the back of the card in the assets folder.
 */
image_back_url: string, };

/**
 * The liability type determines the cost of lending for that particular liability.
 */
export type LiabilityType = "Trade Credit" | "Bank Loan" | "Bonds";

/**
 * Errors that can happen in the lobby phase.
 */
export type LobbyError = { "UsernameAlreadyTaken": string } | "InvalidUsername";

/**
 * The market card type
 */
export type MarketCard = { 
/**
 * The title of the market
 */
title: string, 
/**
 * The rfr value of the market
 */
rfr: number, 
/**
 * The mrp value of the market
 */
mrp: number, 
/**
 * The market condition for yellow
 */
Yellow: MarketCondition, 
/**
 * The market condition for blue
 */
Blue: MarketCondition, 
/**
 * The market condition for green
 */
Green: MarketCondition, 
/**
 * The market condition for purple
 */
Purple: MarketCondition, 
/**
 * The market condition for red
 */
Red: MarketCondition, };

/**
 * Data used when someone buys a new asset and a market change is triggered
 */
export type MarketChange = { 
/**
 * A list of events encountered in search for a market card
 */
events: Array<EventCard>, 
/**
 * The new market card
 */
new_market: MarketCard, };

/**
 * A representation of the market condition for a specific color. It can either be
 * 1. Up: (+)
 * 2. Zero: ( )
 * 3. Minus: (-)
 *
 * NOTE: The default state is `Zero`, which is also the case when parsing with serde.
 */
export type MarketCondition = "up" | "down" | "zero";

/**
 * Errors that can happen when someone plays a card.
 */
export type PlayCardError = { "InvalidCardIndex": number } | "ExceedsMaximumAssets" | "ExceedsMaximumLiabilities" | { "CannotAffordAsset": { 
/**
 * The amount of cash a player has
 */
cash: number, 
/**
 * The cost of the asset
 */
cost: number, } };

/**
 * a representation of how many assets of each color a certain player is allowed to buy this round.
 */
export type PlayableAssets = { total: number, red_cost: number, green_cost: number, purple_cost: number, yellow_cost: number, blue_cost: number, };

/**
 * A wrapper around `u8` which represents a player's `id`.
 */
export type PlayerId = number;

/**
 * Publicly available information for each player. This contains information that you would be able
 * to see from another player if you were looking at what they have on the table. You cannot see
 * their hand, but you can see the amount of asset cards and liability cards they have.
 */
export type PlayerInfo = { 
/**
 * The name of the player.
 */
name: string, 
/**
 * The id of the player.
 */
id: PlayerId, 
/**
 * The hand of the player, represented as different [`CardType`]s.
 */
hand: Array<CardType>, 
/**
 * The assets this player has bought.
 */
assets: Array<AssetCard>, 
/**
 * The liabilities this player has issued.
 */
liabilities: Array<LiabilityCard>, 
/**
 * The amount of cash this player has.
 */
cash: number, 
/**
 * The character this player has chosen, if applicable.
 */
character: CharacterType | null, };

/**
 * Representation of a player's final score, which contains their id as well as their score.
 *
 * # Examples
 *
 * ```
 * # use game::{game::PlayerScore, player::PlayerId};
 * let score = PlayerScore::new(PlayerId(0), "oxey", 10.0);
 * assert_eq!(score.id(), PlayerId(0));
 * assert_eq!(score.name(), "oxey");
 * assert_eq!(score.score(), 10.0);
 * ```
 */
export type PlayerScore = { id: PlayerId, name: string, score: number, };

/**
 * Errors that can happen when redeeming a liability.
 */
export type RedeemLiabilityError = { "NotAllowedToRedeemLiability": CharacterType } | "ExceedsMaximumLiabilities" | { "InvalidLiabilityIndex": number } | { "NotEnoughCash": { 
/**
 * The amount of cash a player has
 */
cash: number, 
/**
 * The cost of the asset
 */
cost: number, } };

/**
 * Utility struct used to represent the amount of asset cards and liability cards a certain player
 * has.
 */
export type RegulatorSwapPlayer = { 
/**
 * The id of the particular player.
 */
player_id: PlayerId, 
/**
 * The amount of asset cards this player has.
 */
asset_count: number, 
/**
 * The amount of liability cards this player has.
 */
liability_count: number, };

/**
 * The general error type that can be sent back in a response.
 */
export type ResponseError = { "Game": GameError } | "GameNotYetStarted" | "GameAlreadyStarted" | "InvalidData";

/**
 * Errors that can happen while selecting characters.
 */
export type SelectingCharactersError = "NotPickingCharacters" | { "AlreadySelectedCharacter": CharacterType } | "UnavailableCharacter" | "NotChairman";

/**
 * A type that represents the changes made with the [`SilverIntoGold`] asset ability. It contains
 * the index of the asset that was changed, as well as its original silver value.
 */
export type SilverIntoGoldData = { 
/**
 * The index of the asset in question.
 */
asset_idx: number, 
/**
 * The gold value of the asset in question.
 */
gold_value: number, 
/**
 * The silver value of the asset in question.
 */
silver_value: number, };

/**
 * Errors related to swapping hands/cards.
 */
export type SwapError = "AlreadySwapedThisTurn" | "InvalidPlayerCharacter" | "InvalidCardIdxs" | "InvalidTargetPlayer";

/**
 * A response type that is meant for every other player when one player performs an action.
 */
export type UniqueResponse = { "action": "PlayersInLobby", "data": { 
/**
 * The name of the player that joined/left.
 */
changed_player: string, 
/**
 * The new list of usernames.
 */
usernames: Array<string>, } } | { "action": "StartGame", "data": { 
/**
 * This player's personal id.
 */
id: PlayerId, 
/**
 * The amount of cash this player gets.
 */
cash: number, 
/**
 * The player's hand.
 */
hand: Array<EitherAssetLiability>, 
/**
 * Public info about every other player.
 */
player_info: Array<PlayerInfo>, 
/**
 * The market at the start of the game.
 */
initial_market: MarketCard, } } | { "action": "SelectingCharacters", "data": { 
/**
 * The id of the chairman, or the person who selects a character first.
 */
chairman_id: PlayerId, 
/**
 * If it's this player's turn, a list of characters that can be selected.
 */
selectable_characters: Array<CharacterType> | null, 
/**
 * A list of characters that cannot be selected by anyone.
 */
open_characters: Array<CharacterType>, 
/**
 * A character that only the chairman can see, but not select.
 */
closed_character: CharacterType | null, 
/**
 * The order each player selects a character in.
 */
turn_order: Array<PlayerId>, } } | { "action": "SelectedCharacter", "data": { 
/**
 * The id of the player that's currently selecting.
 */
currently_picking_id: PlayerId | null, 
/**
 * If it's this player's turn, a list of characters that can be selected.
 */
selectable_characters: Array<CharacterType> | null, 
/**
 * A character that only the chairman can see, but not select.
 */
closed_character: CharacterType | null, } } | { "action": "TurnStarts", "data": { 
/**
 * Id of the player whose turn it is
 */
player_turn: PlayerId, 
/**
 * Extra cash received by the player whose turn it is
 */
player_turn_cash: number, 
/**
 * The amount of cards this player draws.
 */
draws_n_cards: number, 
/**
 * The amount of cards this player gives back.
 */
gives_back_n_cards: number, 
/**
 * The amount of assets this player can play, where each color asset has a different 'unit
 * cost' attached to it.
 */
playable_assets: PlayableAssets, 
/**
 * The amount of liabilities this player can play.
 */
playable_liabilities: number, 
/**
 * The character of this player.
 */
player_character: CharacterType, 
/**
 * A list of characters which were called but were not available.
 */
skipped_characters: Array<CharacterType>, } } | { "action": "DrewCard", "data": { 
/**
 * The id of the player who drew a card.
 */
player_id: PlayerId, 
/**
 * The type of card this player drew.
 */
card_type: CardType, } } | { "action": "PutBackCard", "data": { 
/**
 * The id of the player who put back a card.
 */
player_id: PlayerId, 
/**
 * The type of card this player put back.
 */
card_type: CardType, } } | { "action": "BoughtAsset", "data": { 
/**
 * The id of the player who bought an asset.
 */
player_id: PlayerId, 
/**
 * The asset this player bought.
 */
asset: AssetCard, 
/**
 * If buying the asset changed the market, sends a list of events as well as the new
 * market.
 */
market_change: MarketChange | null, } } | { "action": "IssuedLiability", "data": { 
/**
 * The id of the player who issued a liability
 */
player_id: PlayerId, 
/**
 * The liability this player issued.
 */
liability: LiabilityCard, } } | { "action": "RedeemedLiability", "data": { 
/**
 * The id of the player who
 */
player_id: PlayerId, 
/**
 * The index of the liability this player redeemed.
 */
liability_idx: number, } } | { "action": "ShareholderIsFiring", "data": Record<string, never> } | { "action": "FiredCharacter", "data": { 
/**
 * The id of the player who fired someone.
 */
player_id: PlayerId, 
/**
 * The character which was fired.
 */
character: CharacterType, } } | { "action": "RegulatorSwapedYourCards", "data": { 
/**
 * This player's new hand.
 */
new_cards: Array<EitherAssetLiability>, } } | { "action": "SwapedWithPlayer", "data": { 
/**
 * The id of the regulator.
 */
regulator_id: PlayerId, 
/**
 * The id of the player the regulator swapped their hands with.
 */
target_id: PlayerId, } } | { "action": "SwapedWithDeck", "data": { 
/**
 * The amount of assets the regulator drew from the deck.
 */
asset_count: number, 
/**
 * The amount of liabilities the regulator drew from the deck.
 */
liability_count: number, } } | { "action": "AssetDivested", "data": { 
/**
 * The id of the stakeholder.
 */
player_id: PlayerId, 
/**
 * The id of the player who is forced to divest one of their assets.
 */
target_id: PlayerId, 
/**
 * The index of the asset they are forced to divest.
 */
card_idx: number, 
/**
 * The amount of gold the stakeholder paid to divest this asset.
 */
paid_gold: number, } } | { "action": "TurnEnded", "data": { 
/**
 * The id of the player whose turn ended.
 */
player_id: PlayerId, } } | { "action": "GameEnded", "data": { 
/**
 * A list of player scores.
 */
scores: Array<PlayerScore>, } } | { "action": "MinusedIntoPlus", "data": { 
/**
 * The id of the player which changed one of their market colors.
 */
player_id: PlayerId, 
/**
 * The new market for the player that performed the action,
 */
new_market: MarketCard, 
/**
 * The updated player score.
 */
new_score: number, } } | { "action": "SilveredIntoGold", "data": { 
/**
 * The id of the player which changed the silver of one of their cards into gold.
 */
player_id: PlayerId, 
/**
 * The data of the old asset that should be updated. When no card was selected before this
 * action, this value will be `None`.
 */
old_asset_data: SilverIntoGoldData | null, 
/**
 * The data of the new asset that should be updated. When a card was deselected, this value
 * will be `None`.
 */
new_asset_data: SilverIntoGoldData | null, 
/**
 * The updated player score.
 */
new_score: number, } } | { "action": "ChangedAssetColor", "data": { 
/**
 * The id of the player which changed the color of one of their assets.
 */
player_id: PlayerId, 
/**
 * The data of the old asset that should be updated. When no card was selected before this
 * action, this value will be `None`.
 */
old_asset_data: ChangeAssetColorData | null, 
/**
 * The data of the new asset that should be updated. When a card was deselected, this value
 * will be `None`.
 */
new_asset_data: ChangeAssetColorData | null, 
/**
 * The updated player score.
 */
new_score: number, } } | { "action": "ConfirmedAssetAbility", "data": { 
/**
 * The id of the player which confirmed an asset ability's choice.
 */
player_id: PlayerId, 
/**
 * The asset the player confirmed their choice for.
 */
asset_idx: number, } };
