name: Linux_Container_Workflow
on:
  push:
    branches: [ "cd" ]
  pull_request:
    branches: [ "cd" ]

env:
  VITE_BOTTOM_ONLINE_BACKEND_URL: ${{ secrets.BACKEND_URL }}
  VITE_TEST: 3

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
          with:
            ref: cd

        - name: Install dependencies
          run: npm install
          
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        
        - name: 'Build and push image'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        - run: |
            docker build .
              --build-arg VITE_BOTTOM_ONLINE_BACKEND_URL=${{ secrets.BACKEND_URL }}
              --build-arg VITE_TEST=3
              -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/frontend:${{ github.sha }}
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/frontend:${{ github.sha }}

        - name: 'Deploy to Azure Container Instances'
          uses: 'azure/aci-deploy@v1'
          with:
            resource-group: ${{ secrets.RESOURCE_GROUP }}
            dns-name-label: bottomonline
            image: ${{ secrets.REGISTRY_LOGIN_SERVER }}/frontend:${{ github.sha }}
            registry-login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            registry-username: ${{ secrets.REGISTRY_USERNAME }}
            registry-password: ${{ secrets.REGISTRY_PASSWORD }}
            name: autofrontend
            location: 'germanywestcentral'
            cpu: 0.1
            memory: 0.5
